repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: poetry run black --check src tests
          always_run: true
          pass_filenames: false
          language: system
        - id: isort
          name: isort
          entry: poetry run isort -c src tests
          always_run: true
          pass_filenames: false
          language: system
        - id: flake8
          name: flake8
          entry: poetry run flake8 src tests
          always_run: true
          pass_filenames: false
          language: system
        - id: mypy
          name: mypy
          entry: poetry run mypy
          always_run: true
          language: system
          pass_filenames: false
          verbose: true